package com.jnzy.mdm.bean.mobileButler;

import java.io.Serializable;
import java.util.Date;

public class MBackupRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_backup_record.backup_id
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    private Integer backupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_backup_record.device_id
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_backup_record.mobile
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_backup_record.type
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_backup_record.create_time
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_backup_record.file_md5
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    private String fileMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_backup_record
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_backup_record.backup_id
     *
     * @return the value of m_backup_record.backup_id
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    public Integer getBackupId() {
        return backupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_backup_record.backup_id
     *
     * @param backupId the value for m_backup_record.backup_id
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    public void setBackupId(Integer backupId) {
        this.backupId = backupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_backup_record.device_id
     *
     * @return the value of m_backup_record.device_id
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_backup_record.device_id
     *
     * @param deviceId the value for m_backup_record.device_id
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_backup_record.mobile
     *
     * @return the value of m_backup_record.mobile
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_backup_record.mobile
     *
     * @param mobile the value for m_backup_record.mobile
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_backup_record.type
     *
     * @return the value of m_backup_record.type
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_backup_record.type
     *
     * @param type the value for m_backup_record.type
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_backup_record.create_time
     *
     * @return the value of m_backup_record.create_time
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_backup_record.create_time
     *
     * @param createTime the value for m_backup_record.create_time
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_backup_record.file_md5
     *
     * @return the value of m_backup_record.file_md5
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    public String getFileMd5() {
        return fileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_backup_record.file_md5
     *
     * @param fileMd5 the value for m_backup_record.file_md5
     *
     * @mbggenerated Thu Dec 22 15:12:59 CST 2016
     */
    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5;
    }
}