package com.jnzy.mdm.bean.mobileButler;

import java.io.Serializable;
import java.util.Date;

public class MContactsBackup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_contacts_backup00.concact_id
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    private Integer contactId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_contacts_backup00.device_id
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_contacts_backup00.mobile
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_contacts_backup00.create_time
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_contacts_backup00.contact
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_contacts_backup00.call_number
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    private String callNumber;

    private String addTime;

    private Integer userId;
    private Integer organId;


    public String getAddTime() {
        return addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getOrganId() {
        return organId;
    }

    public void setOrganId(Integer organId) {
        this.organId = organId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_contacts_backup00
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_contacts_backup00.concact_id
     *
     * @return the value of m_contacts_backup00.concact_id
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    public Integer getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_contacts_backup00.concact_id
     *
     * @param contactId the value for m_contacts_backup00.concact_id
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_contacts_backup00.device_id
     *
     * @return the value of m_contacts_backup00.device_id
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_contacts_backup00.device_id
     *
     * @param deviceId the value for m_contacts_backup00.device_id
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_contacts_backup00.mobile
     *
     * @return the value of m_contacts_backup00.mobile
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_contacts_backup00.mobile
     *
     * @param mobile the value for m_contacts_backup00.mobile
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_contacts_backup00.create_time
     *
     * @return the value of m_contacts_backup00.create_time
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_contacts_backup00.create_time
     *
     * @param createTime the value for m_contacts_backup00.create_time
     *
     * @mbggenerated Tue Dec 20 13:30:17 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getCallNumber() {
        return callNumber;
    }

    public void setCallNumber(String callNumber) {
        this.callNumber = callNumber;
    }
}