package com.jnzy.mdm.bean.mobileButler;

import java.io.Serializable;
import java.util.Date;

public class MSmsBackup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_backup00.sms_id
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    private Integer smsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_backup00.device_id
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_backup00.mobile
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_backup00.create_time
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_backup00.type
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_backup00.add_time
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_backup00.number
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    private String receiveNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sms_backup00.content
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    private String content;

    private String contact;//联系人

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    private Integer userId;
    private Integer organId;

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getOrganId() {
        return organId;
    }

    public void setOrganId(Integer organId) {
        this.organId = organId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_sms_backup00
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_backup00.sms_id
     *
     * @return the value of m_sms_backup00.sms_id
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    public Integer getSmsId() {
        return smsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_backup00.sms_id
     *
     * @param smsId the value for m_sms_backup00.sms_id
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    public void setSmsId(Integer smsId) {
        this.smsId = smsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_backup00.device_id
     *
     * @return the value of m_sms_backup00.device_id
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_backup00.device_id
     *
     * @param deviceId the value for m_sms_backup00.device_id
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_backup00.mobile
     *
     * @return the value of m_sms_backup00.mobile
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_backup00.mobile
     *
     * @param mobile the value for m_sms_backup00.mobile
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_backup00.create_time
     *
     * @return the value of m_sms_backup00.create_time
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_backup00.create_time
     *
     * @param createTime the value for m_sms_backup00.create_time
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_backup00.type
     *
     * @return the value of m_sms_backup00.type
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sms_backup00.add_time
     *
     * @return the value of m_sms_backup00.add_time
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sms_backup00.add_time
     *
     * @param addTime the value for m_sms_backup00.add_time
     *
     * @mbggenerated Tue Dec 20 13:27:43 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public String getReceiveNumber() {
        return receiveNumber;
    }

    public void setReceiveNumber(String receiveNumber) {
        this.receiveNumber = receiveNumber;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
}