package com.jnzy.mdm.bean.other;

import java.io.Serializable;
import java.util.Date;

public class MAppPushUsermodelTag implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_app_push_usermodel_tag.push_user_tag_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    private Integer pushUserTagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_app_push_usermodel_tag.user_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_app_push_usermodel_tag.device_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_app_push_usermodel_tag.model_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    private String modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_app_push_usermodel_tag.is_success
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    private Integer isSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_app_push_usermodel_tag.add_time
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_app_push_usermodel_tag.registration_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    private String registrationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_app_push_usermodel_tag
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_app_push_usermodel_tag.push_user_tag_id
     *
     * @return the value of m_app_push_usermodel_tag.push_user_tag_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    public Integer getPushUserTagId() {
        return pushUserTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_app_push_usermodel_tag.push_user_tag_id
     *
     * @param pushUserTagId the value for m_app_push_usermodel_tag.push_user_tag_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    public void setPushUserTagId(Integer pushUserTagId) {
        this.pushUserTagId = pushUserTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_app_push_usermodel_tag.user_id
     *
     * @return the value of m_app_push_usermodel_tag.user_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_app_push_usermodel_tag.user_id
     *
     * @param userId the value for m_app_push_usermodel_tag.user_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_app_push_usermodel_tag.device_id
     *
     * @return the value of m_app_push_usermodel_tag.device_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_app_push_usermodel_tag.device_id
     *
     * @param deviceId the value for m_app_push_usermodel_tag.device_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_app_push_usermodel_tag.model_id
     *
     * @return the value of m_app_push_usermodel_tag.model_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_app_push_usermodel_tag.model_id
     *
     * @param modelId the value for m_app_push_usermodel_tag.model_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    public void setModelId(String modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_app_push_usermodel_tag.is_success
     *
     * @return the value of m_app_push_usermodel_tag.is_success
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    public Integer getIsSuccess() {
        return isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_app_push_usermodel_tag.is_success
     *
     * @param isSuccess the value for m_app_push_usermodel_tag.is_success
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    public void setIsSuccess(Integer isSuccess) {
        this.isSuccess = isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_app_push_usermodel_tag.add_time
     *
     * @return the value of m_app_push_usermodel_tag.add_time
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_app_push_usermodel_tag.add_time
     *
     * @param addTime the value for m_app_push_usermodel_tag.add_time
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_app_push_usermodel_tag.registration_id
     *
     * @return the value of m_app_push_usermodel_tag.registration_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    public String getRegistrationId() {
        return registrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_app_push_usermodel_tag.registration_id
     *
     * @param registrationId the value for m_app_push_usermodel_tag.registration_id
     *
     * @mbggenerated Thu Jan 12 14:05:24 CST 2017
     */
    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }
}